### ISSUE TITLE
Planning to use external sources for quotes yet?

### ISSUE THREAD

**Issue by deXterbed** [macalinao/motivate#3]

**Comment by simplyianm** [comment]
I could. What source should I get them from?

**Comment by deXterbed** [comment]
https://www.mashape.com/andruxnet/random-famous-quotes

**Comment by deXterbed** [comment]
These guys have a good collection too `https://twitter.com/GreatestQuotes`, we can use twitter API to get the daily quotes from there.

**Comment by macalinao** [comment]
Interesting, but I think it's best for this to work offline.
